- name: Authorize ROS GPG key
  become: true
  ansible.builtin.get_url:
    url: https://raw.githubusercontent.com/ros/rosdistro/master/ros.key
    dest: /usr/share/keyrings/ros-archive-keyring.gpg
    mode: 0644

- name: Save result of 'dpkg --print-architecture'
  ansible.builtin.command: dpkg --print-architecture
  register: ros2__deb_architecture
  changed_when: false

- name: Save result of Ubuntu codename
  ansible.builtin.shell: bash -c 'source /etc/os-release && echo $UBUNTU_CODENAME'
  register: ros2__ubuntu_codename
  changed_when: false

- name: Add ROS 2 apt repository
  become: true
  ansible.builtin.apt_repository:
    repo: deb [arch={{ ros2__deb_architecture.stdout }} signed-by=/usr/share/keyrings/ros-archive-keyring.gpg] http://packages.ros.org/ros2/ubuntu {{ ros2__ubuntu_codename.stdout }} main
    filename: ros2
    state: present
    update_cache: true

- name: Install basic dependencies
  become: true
  ansible.builtin.apt:
    name:
      - curl
      - gnupg
      - lsb-release
      - apt-utils
      - build-essential
      - git
    state: present
    update_cache: true

- name: Install ROS2 development dependencies
  become: true
  ansible.builtin.apt:
    name:
      - cmake
      - libbullet-dev
      - libpython3-dev
      - python3-flake8
      - python3-pip
      - python3-numpy
      - python3-pytest-cov
      - python3-setuptools
      - python3-vcstool
      - python3-rosinstall-generator
      - libasio-dev
      - libtinyxml2-dev
      - libcunit1-dev
      - libpugixml-dev
      - libgeographic-dev
      - libgtest-dev
      - libcgal-dev
      - libfmt-dev
    state: present

- name: Install EmPy with specific version
  become: true
  ansible.builtin.pip:
    name: empy==3.3.4
    extra_args: --no-cache-dir

- name: Install Python dependencies
  become: true
  ansible.builtin.pip:
    name:
      - argcomplete
      - pytest
      - pytest-repeat
      - pytest-rerunfailures
      - scikit-build
      - cmake==3.31.6
    extra_args: --upgrade --no-cache-dir

- name: Install Python code quality tools
  become: true
  ansible.builtin.pip:
    name:
      - flake8-blind-except
      - flake8-builtins
      - flake8-class-newline
      - flake8-comprehensions
      - flake8-deprecated
      - flake8-docstrings
      - flake8-import-order
      - flake8-quotes
    extra_args: --upgrade --no-cache-dir

- name: Install ROS2 {{ rosdistro }}
  become: true
  ansible.builtin.apt:
    name: ros-{{ rosdistro }}-{{ installation_type }}
    state: present
    update_cache: true

- name: Install ROS2 tools
  become: true
  ansible.builtin.apt:
    name:
      - python3-rosdep
      - python3-colcon-common-extensions
      - ros-{{ rosdistro }}-rmw-cyclonedds-cpp
    state: present

- name: Add ROS2 setup to .bashrc
  ansible.builtin.lineinfile:
    dest: ~/.bashrc
    line: source /opt/ros/{{ rosdistro }}/setup.bash
    state: present
    create: true
    mode: 0644

- name: Initialize rosdep
  become: true
  ansible.builtin.command: rosdep init
  args:
    creates: /etc/ros/rosdep/sources.list.d/20-default.list
  ignore_errors: true

- name: Update rosdep
  ansible.builtin.command: rosdep update
  changed_when: false
