# ROS distro to build from source (e.g. jazzy for Ubuntu 22.04).
rosdistro: jazzy
ros_variant: ros_base # detailed ros_variant is defined in https://www.ros.org/reps/rep-2001.html#jazzy-jalisco-may-2024-may-2029
# Workspace directory (src, build, log). Install goes to /opt/ros/{{ rosdistro }} via --install-base.
source_build_workspace_dir: "{{ ansible_env.HOME }}/source_builds_ws"

# Additional ROS packages imported with rosinstall_generator.
extra_rosinstall_packages:
  - camera_calibration_parsers
  - camera_info_manager
  - cv_bridge
  - vision_opencv
  - geographic_msgs
  - vision_msgs
  - image_geometry
  - image-transport
  - pcl_msgs
  - perception_pcl
  - logging_demo # https://github.com/autowarefoundation/autoware_utils/blob/f3c8f34264fe4812da406ab0390e65c95ec386ab/autoware_utils_logging/include/autoware_utils_logging/logger_level_configure.hpp#L44
  - udp_msgs
  - angles
  - diagnostics
  - tf_transformations
  - grid_map
  - filters
  - nav2_msgs
  - ffmpeg_image_transport_msgs # Required for accelerated_image_processor_ros
  - tl_expected
  # - v4l2_camera # already included in edge-auto-jetson.repos
  # - image_pipeline # already included in edge-auto-jetson.repos
  # - mrt_cmake_modules # already included in edge-auto-jetson.repos
  # - compressed_image_transport  # already included in edge-auto-jetson.repos
  # - compressed_depth_image_transport  # already included in edge-auto-jetson.repos

# Extra system libraries needed by the selected extra ROS packages.
extra_system_packages:
  - cmake # from https://github.com/tier4/edge-auto-jetson/blob/beta/anvil/v0.48.0/ansible/roles/ros2/tasks/main.yaml#L39-L61
  - libbullet-dev
  - libpython3-dev
  - python3-flake8
  - python3-pip
  - python3-numpy
  - python3-setuptools
  - python3-vcstool
  - python3-rosinstall-generator
  - libasio-dev
  - libtinyxml2-dev
  - libcunit1-dev
  - libpugixml-dev
  - libgeographic-dev
  - libgtest-dev
  - libcgal-dev
  - libfmt-dev
  - python3-rosdep # https://github.com/tier4/edge-auto-jetson/blob/beta/anvil/v0.48.0/ansible/roles/ros2/tasks/main.yaml#L133
  - python3-colcon-common-extensions
  - librange-v3-dev
  - v4l-utils
  - nlohmann-json3-dev
  - nvidia-jetpack # Install CUDA and dependencies.
  - libavfilter-dev # Required for accelerated_image_processor_decompression
  - libturbojpeg0-dev # Required for accelerated_image_processor
  - libavdevice-dev # Required for accelerated_image_processor

# Extra Python packages needed by the selected extra ROS packages.
extra_python_packages:
  - empy==3.3.4 # https://github.com/tier4/edge-auto-jetson/blob/beta/anvil/v0.48.0/ansible/roles/ros2/tasks/main.yaml#L63
  - argcomplete # https://github.com/tier4/edge-auto-jetson/blob/beta/anvil/v0.48.0/ansible/roles/ros2/tasks/main.yaml#L69
  - pytest
  - pytest-repeat
  - pytest-rerunfailures
  - scikit-build
  - cmake==3.31.6
  - flake8-blind-except # https://github.com/tier4/edge-auto-jetson/blob/beta/anvil/v0.48.0/ansible/roles/ros2/tasks/main.yaml#L81
  - flake8-builtins
  - flake8-class-newline
  - flake8-comprehensions
  - flake8-deprecated
  - flake8-docstrings
  - flake8-import-order
  - flake8-quotes
