#
# The following sequence modifies configuration items if it exists in {{ target_file }},
# or add it to the end of line starting with {{ config_prefix }} if it not exist
#
- name: Check item existence
  ansible.builtin.lineinfile:
    dest: "{{ target_file }}"
    regexp: ^(.*){{ target_item }}={{ target_val }}(.*)$
    state: absent
  check_mode: true
  changed_when: false
  register: does_exist
  become: true

- name: Modify
  ansible.builtin.lineinfile:
    dest: "{{ target_file }}"
    regexp: ^(.*) {{ target_item }}=[a-z0-9]* (.*)$
    line: \1 {{ target_item }}={{ target_val }} \2 # Yaml requires escaping backslashes in double quotes but not in single quotes
    backrefs: true
  register: is_modified
  become: true

- name: Add
  ansible.builtin.lineinfile:
    dest: "{{ target_file }}"
    regexp: ^({{ config_prefix }})(.*)$
    line: \1\2 {{ target_item }}={{ target_val }}
    backrefs: true
  when: not does_exist.found and not is_modified.changed
  become: true
