- name: Create cyclonedds directory
  ansible.builtin.file:
    path: /opt/autoware/cyclonedds
    state: directory
    mode: 0755
  become: true

- name: Copy config
  ansible.builtin.template:
    src: cyclonedds.xml.jinja2
    dest: /opt/autoware/cyclonedds/cyclonedds.xml
    mode: 0755
  become: true

- name: Add settings to autoware.env
  ansible.builtin.blockinfile:
    path: "{{ autoware_env_dir }}/autoware.env"
    state: present
    create: true
    mode: 0644
    marker: "# {mark} cyclonedds"
    block: |
      export RMW_IMPLEMENTATION=rmw_cyclonedds_cpp
      export CYCLONEDDS_URI=file:///opt/autoware/cyclonedds/cyclonedds.xml
  become: true
