# tensorrt_yolox
- name: Create tensorrt_yolox directory inside {{ data_dir }}
  ansible.builtin.file:
    path: "{{ data_dir }}/tensorrt_yolox"
    mode: "755"
    state: directory

- name: Download tensorrt_yolox/yolox-tiny.onnx
  become: true
  ansible.builtin.get_url:
    url: https://awf.ml.dev.web.auto/perception/models/yolox-tiny.onnx
    dest: "{{ data_dir }}/tensorrt_yolox/yolox-tiny.onnx"
    mode: "644"
    checksum: sha256:471a665f4243e654dff62578394e508db22ee29fe65d9e389dfc3b0f2dee1255

- name: Download tensorrt_yolox/yolox-sPlus-opt.onnx
  become: true
  ansible.builtin.get_url:
    url: https://awf.ml.dev.web.auto/perception/models/yolox-sPlus-opt.onnx
    dest: "{{ data_dir }}/tensorrt_yolox/yolox-sPlus-opt.onnx"
    mode: "644"
    checksum: sha256:36b0832177b01e6b278e00c7369f1de71e616c36261cbae50f0753d41289da01

- name: Download tensorrt_yolox/yolox-sPlus-opt.EntropyV2-calibration.table
  become: true
  ansible.builtin.get_url:
    url: https://awf.ml.dev.web.auto/perception/models/yolox-sPlus-opt.EntropyV2-calibration.table
    dest: "{{ data_dir }}/tensorrt_yolox/yolox-sPlus-opt.EntropyV2-calibration.table"
    mode: "644"
    checksum: sha256:b9e9d7da33342262ccaea4469b4d02b8abb32b6d7bf737f9e0883fece1b8f580

- name: Download tensorrt_yolox/yolox-sPlus-T4-960x960-pseudo-finetune.onnx
  become: true
  ansible.builtin.get_url:
    url: https://awf.ml.dev.web.auto/perception/models/object_detection_yolox_s/v1/yolox-sPlus-T4-960x960-pseudo-finetune.onnx
    dest: "{{ data_dir }}/tensorrt_yolox/yolox-sPlus-T4-960x960-pseudo-finetune.onnx"
    mode: "644"
    checksum: sha256:f5054e8a890c3be86dc1b4b89a5a36fb2279d4f6110b0159e793be062641bf65

- name: Download tensorrt_yolox/yolox-sPlus-T4-960x960-pseudo-finetune.EntropyV2-calibration.table
  become: true
  ansible.builtin.get_url:
    url: https://awf.ml.dev.web.auto/perception/models/object_detection_yolox_s/v1/yolox-sPlus-T4-960x960-pseudo-finetune.EntropyV2-calibration.table
    dest: "{{ data_dir }}/tensorrt_yolox/yolox-sPlus-T4-960x960-pseudo-finetune.EntropyV2-calibration.table"
    mode: "644"
    checksum: sha256:cc378d327db5616b0b3a4d077bf37100c25a50ecd22d2b542f54098da100f34c

- name: Download tensorrt_yolox/label.txt
  become: true
  ansible.builtin.get_url:
    url: https://awf.ml.dev.web.auto/perception/models/label.txt
    dest: "{{ data_dir }}/tensorrt_yolox/label.txt"
    mode: "644"
    checksum: sha256:3540a365bfd6d8afb1b5d8df4ec47f82cb984760d3270c9b41dbbb3422d09a0c

- name: Download tensorrt_yolox/yolox-sPlus-opt-pseudoV2-T4-960x960-T4-seg16cls.onnx
  become: true
  ansible.builtin.get_url:
    url: https://awf.ml.dev.web.auto/perception/models/object_detection_semseg_yolox_s/v1/yolox-sPlus-opt-pseudoV2-T4-960x960-T4-seg16cls.onnx
    dest: "{{ data_dir }}/tensorrt_yolox/yolox-sPlus-opt-pseudoV2-T4-960x960-T4-seg16cls.onnx"
    mode: "644"
    checksum: sha256:73b3812432cedf65cebf02ca4cb630542fc3b1671c4c0fbf7cee50fa38e416a8

- name: Download tensorrt_yolox/yolox-sPlus-opt-pseudoV2-T4-960x960-T4-seg16cls.EntropyV2-calibration.table
  become: true
  ansible.builtin.get_url:
    url: https://awf.ml.dev.web.auto/perception/models/object_detection_semseg_yolox_s/v1/yolox-sPlus-opt-pseudoV2-T4-960x960-T4-seg16cls.EntropyV2-calibration.table
    dest: "{{ data_dir }}/tensorrt_yolox/yolox-sPlus-opt-pseudoV2-T4-960x960-T4-seg16cls.EntropyV2-calibration.table"
    mode: "644"
    checksum: sha256:28cd6524d4bcdb2809592a225d28330433e58dc02c92169ea555b44c1a51a584

- name: Download tensorrt_yolox/semseg_color_map.csv
  become: true
  ansible.builtin.get_url:
    url: https://awf.ml.dev.web.auto/perception/models/object_detection_semseg_yolox_s/v1/semseg_color_map.csv
    dest: "{{ data_dir }}/tensorrt_yolox/semseg_color_map.csv"
    mode: "644"
    checksum: sha256:3d93ca05f31b63424d7d7246a01a2365953705a0ed3323ba5b6fddd744a4bfea
