- name: Fetch package repos
  block:
    - name: Download setup script
      ansible.builtin.uri:
        url: https://packagecloud.io/install/repositories/dirk-thomas/vcstool/script.deb.sh
        return_content: true
      register: script_deb_sh
    - name: Execute setup script
      ansible.builtin.cmd: bash "{{ script_deb_sh.content }}"
      become: true
      # noqa no-changed-when
      # TODO: check vcstool existing

- name: Install apt packages
  ansible.builtin.apt:
    name:
      - python3-vcstool
    update_cache: true
  become: true
