- name: Fetch package repos
  block:
    - name: Download setup script
      ansible.builtin.uri:
        url: https://packagecloud.io/install/repositories/dirk-thomas/vcstool/script.deb.sh
        return_content: yes
      register: script_deb_sh
    - name: Execute setup script
      ansible.builtin.shell:
        cmd: bash
        stdin: "{{ script_deb_sh.content }}"
      become: true

- name: Install apt packages
  become: true
  ansible.builtin.apt:
    name:
      - python3-vcstool
    update_cache: true
