- name: Fetch package repos
  block:
    - name: Download setup script
      ansible.builtin.uri:
        url: https://packagecloud.io/install/repositories/dirk-thomas/vcstool/script.deb.sh
        dest: "{{ vcstool_script_download_dir }}"
        mode: 0755
      register: script_deb_sh
    - name: Execute setup script
      ansible.builtin.command: bash {{ vcstool_script_download_dir }}/script.deb.sh
      become: true
      # noqa no-changed-when
      # TODO: check vcstool existing

- name: Install apt packages
  ansible.builtin.apt:
    name:
      - python3-vcstool
    update_cache: true
  become: true
