- name: Fix python interpreter version to 3
  ansible.builtin.set_fact:
    ansible_python_interpreter: /usr/bin/python3.6

- name: Upgrade pip
  ansible.builtin.pip:
    name: pip
    state: latest

- name: Install dependencies
  ansible.builtin.pip:
    name:
      - dt-apriltags
      - ruamel.yaml
    state: latest

- name: Download PySide2 wheel
  ansible.builtin.uri:
    url: "{{ calibration_tools_pyside2_url_base }}/{{ calibration_tools_pyside2_wheel }}"
    dest: "{{ calibration_tools_pyside2_download_dir }}/{{ calibration_tools_pyside2_wheel }}"
    mode: 0644

- name: Install PySide2
  ansible.builtin.pip:
    name: "{{ calibration_tools_pyside2_download_dir }}/{{ calibration_tools_pyside2_wheel }}"
    state: latest
